This is the test case for 7-base Geometry 

first let's import and test it's type

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
    >>> base_geometry = BaseGeometry()
    >>> type(base_geometry)
    <class '7-base_geometry.BaseGeometry'>

****** we can't have argument inside our base Geometry

    >>> base_geometry = BaseGeometry(22)
    Traceback (most recent call last):
    TypeError: BaseGeometry() takes no arguments

    >>> print(base_geometry) # doctest: +ELLIPSIS
    <7-base_geometry.BaseGeometry object at ...>

********* tesing for none case 

    >>> base_geometry = BaseGeometry(None)
    Traceback (most recent call last):
    TypeError: BaseGeometry() takes no arguments

    ******* test for area ******

    >>> base_geometry.area()
    Traceback (most recent call last):
    Exception: area() is not implemented

**** let's know about it

    >>> base_geometry = BaseGeometry()
    >>> print(base_geometry.area) # doctest: +ELLIPSIS, +NORMALIZE_WHITESPACE
    <bound method BaseGeometry.area of <7-base_geometry.BaseGeometry 
     object at...>>

****** test for integer valdater ****

*** let's know about it 

    >>> print(base_geometry.integer_validator) # doctest: +ELLIPSIS, +NORMALIZE_WHITESPACE
    <bound method BaseGeometry.integer_validator of <7-base_geometry.BaseGeometry 
    object at...>>


**** testing number value

   >>> base_geometry.integer_validator("two", 2)

*** testing non number value

    >>> base_geometry.integer_validator("two", "two")
    Traceback (most recent call last):
    TypeError: two must be an integer

**** test for list tuples and other data strucures 



    >>> base_geometry.integer_validator("invalid number", "number")
    Traceback (most recent call last):
    TypeError: invalid number must be an integer



    >>> base_geometry.integer_validator("another invalid", True)
    Traceback (most recent call last):
    TypeError: another invalid must be an integer



    >>> base_geometry.integer_validator("invalid tuple", (1,))
    Traceback (most recent call last):
    TypeError: invalid tuple must be an integer



    >>> base_geometry.integer_validator("and another", [3])
    Traceback (most recent call last):
    TypeError: and another must be an integer



    >>> base_geometry.integer_validator("more invalid testing", {3, 4})
    Traceback (most recent call last):
    TypeError: more invalid testing must be an integer



    >>> base_geometry.integer_validator("absolutely every possible invalid", None)
    Traceback (most recent call last):
    TypeError: absolutely every possible invalid must be an integer

*** test for none  case 

    >>> base_geometry.integer_validator("not number", None)
    Traceback (most recent call last):
    TypeError: not number must be an integer

**** testing for value less than 0 

**** test for negative number

    >>> base_geometry.integer_validator("mines one", -1)
    Traceback (most recent call last):
    ValueError: mines one must be greater than 0


    >>> base_geometry.integer_validator("zero", 0)
    Traceback (most recent call last):
    ValueError: zero must be greater than 0

